package handlers

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/jung-kurt/gofpdf"
	"mediq/internal/database"
	"mediq/internal/models"
)

// DownloadReport handles GET /api/v1/bookings/:ref/report
func DownloadReport(c *gin.Context) {
	ref := c.Param("ref")
	
	var booking models.Booking
	if err := database.DB.Where("booking_ref = ?", ref).First(&booking).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Booking not found"})
		return
	}

	// Fetch hospital details
	var hospital models.Hospital
	database.DB.First(&hospital, booking.HospitalID)

	// Fetch service details
	var service models.ServicePrice
	database.DB.Where("hospital_id = ? AND service_id = ?", booking.HospitalID, booking.ServiceID).First(&service)

	// Generate PDF
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	
	// Header
	pdf.SetFont("Arial", "B", 24)
	pdf.CellFormat(190, 15, "MediQ Diagnostic Report", "", 1, "C", false, 0, "")
	
	pdf.SetFont("Arial", "I", 12)
	pdf.CellFormat(190, 10, "Mock Medical Report for Resume Demo", "", 1, "C", false, 0, "")
	pdf.Ln(10)

	// Hospital Info
	pdf.SetFont("Arial", "B", 14)
	pdf.CellFormat(190, 10, hospital.Name, "", 1, "L", false, 0, "")
	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(190, 8, hospital.Address, "", 1, "L", false, 0, "")
	pdf.CellFormat(190, 8, "Phone: "+hospital.Phone, "", 1, "L", false, 0, "")
	pdf.Ln(10)

	// Patient Info
	pdf.SetFont("Arial", "B", 14)
	pdf.CellFormat(190, 10, "Patient Details", "", 1, "L", false, 0, "")
	pdf.SetFont("Arial", "", 12)
	pdf.CellFormat(95, 8, "Name: "+booking.PatientName, "", 0, "L", false, 0, "")
	pdf.CellFormat(95, 8, fmt.Sprintf("Age/Gender: %d / %s", booking.PatientAge, booking.PatientGender), "", 1, "L", false, 0, "")
	pdf.CellFormat(95, 8, "Phone: "+booking.PatientPhone, "", 0, "L", false, 0, "")
	pdf.CellFormat(95, 8, "Booking Ref: "+booking.BookingRef, "", 1, "L", false, 0, "")
	pdf.Ln(10)

	// Test Results
	pdf.SetFont("Arial", "B", 16)
	pdf.CellFormat(190, 10, "Test: "+service.ServiceName, "", 1, "C", false, 0, "")
	pdf.Ln(5)

	pdf.SetFont("Arial", "", 12)
	pdf.MultiCell(190, 8, "This is a computer-generated mock diagnostic report. In a real-world application, this section would contain the actual medical findings, parameters, ranges, and doctor's remarks uploaded by the hospital's LIS (Laboratory Information System).", "", "L", false)
	pdf.Ln(10)
	
	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(190, 8, "Result: ALL PARAMETERS NORMAL", "", 1, "L", false, 0, "")

	// Footer
	pdf.SetY(260)
	pdf.SetFont("Arial", "I", 10)
	pdf.CellFormat(190, 10, "Generated by MediQ App", "", 0, "C", false, 0, "")

	// Output
	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=report_%s.pdf", booking.BookingRef))
	
	if err := pdf.Output(c.Writer); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to generate report"})
	}
}
